### ISSUE TITLE
Bug-admin page requires user to click on tab

### ISSUE THREAD

**Issue by Kattily-eng** [CMPUT301F24nebula0/nebula0-events#159]
in total when first entering  the admin manage system the list displayed is non clickable and a user must click on the disired button in order for it to be clickable this occurs again when one goes from the back button  from the event detail admin page to the manage admin page, if you attempt it reapeatable the app will eventually crash .

**Comment by stephuofa** [comment]
If we do a tab views refactor and code consolidation, we may not need to address this bug directly

**Comment by ELi1012** [comment]
thanks for noticing this bug, PR #200 fixes this by using `performClick` on the manage events button during initialization, which enables the admin to interact with these events from the start.
